export { productsAPI as ProductService } from './products.service'
export { collectionsAPI as CollectionService } from './collections.service'
export { photosAPI as PhotosService } from './photos.service'
export { authAPI as AuthService } from './auth.service'
export { ordersAPI as OrdersService } from './orders.service'
export { textBlocksAPI as TextBlocksService } from './text_blocks.service'
