export { HomePage } from './Home'
export { Login } from './Auth/Login'
export { Register } from './Auth/Register'
export { ProductsList as ProductsPage } from './Products'
export { ProductPage } from './Products/ProductPage'
export { CreateProductPage } from './Products/CreateProduct'
export { CollectionsList as CollectionsPage } from './Collections'
export { CollectionPage } from './Collections/CollectionPage'
export { CreateCollectionPage } from './Collections/CreateCollection'
export { OrdersPage } from './Orders'
export { OrderPage } from './Orders/OrderPage'
export { CreateOrderPage } from './Orders/CreateOrder'
